# crop-predict

Use the "Run" button to execute the code.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
# Execute this to save new versions of the notebook
jovian.commit(project="crop-predict")

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/btech60309-19/crop-predict

'https://jovian.ai/btech60309-19/crop-predict'

In [ ]:
from urllib.request import urlretrieve

In [ ]:
urlretrieve('https://drive.google.com/file/d/1_QjuGYzl4HTpRU4RXskw97ij0dPdFK5F/view?usp=sharing','crop1.csv')

('crop1.csv', <http.client.HTTPMessage at 0x7fc6d0cb1f10>)

In [ ]:
import os

In [ ]:
os.listdir()

['.config', 'crop1.csv', 'crop.csv', 'sample_data']

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('./crop.csv')

In [ ]:
df

,S.No.,State,Temperature,Rainfall,Soil PH,soil type,Crop,Yeild
0,1,J&K,26.6,87.3,7.8,alluvial,corn,1.1
1,2,J&K,28.7,80.4,7.8,alluvial,pulse,1.8
2,3,J&K,27.3,85.6,7.9,alluvial,millet,2.1
3,4,Himachal Pradesh,24.5,129.0,6.0,brown hill,rice,21.0
4,5,Himachal Pradesh,24.4,129.0,6.7,brown hill,wheat,80.0
...,...,...,...,...,...,...,...,...
70,71,Karnataka,30.0,1876.0,7.9,red soil,pulse,15.5
71,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.describe()

           S.No.  Temperature     Rainfall    Soil PH       Yeild
count  75.000000    71.000000    71.000000  71.000000   71.000000
mean   38.000000    32.380282  1027.947887   6.866620   33.821972
std    21.794495     8.393988   523.278495   1.062699   51.269530
min     1.000000    15.000000    80.400000   4.200000    1.100000
25%    19.500000    26.000000   649.000000   6.000000    5.125000
50%    38.000000    30.000000  1017.000000   6.700000   17.000000
75%    56.500000    37.500000  1477.500000   7.800000   38.700000
max    75.000000    55.000000  1876.000000   8.760000  340.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   S.No.        75 non-null     int64
 1   State        71 non-null     object
 2   Temperature  71 non-null     float64
 3   Rainfall     71 non-null     float64
 4   Soil PH      71 non-null     float64
 5   soil type    71 non-null     object
 6   Crop         71 non-null     object
 7   Yeild        71 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 4.8+ KB

In [ ]:
df.isna().sum()

S.No.          0
State          4
Temperature    4
Rainfall       4
Soil PH        4
soil type      4
Crop           4
Yeild          4
dtype: int64

In [ ]:
df=df.dropna()
df

,S.No.,State,Temperature,Rainfall,Soil PH,soil type,Crop,Yeild
0,1,J&K,26.6,87.3,7.8,alluvial,corn,1.10
1,2,J&K,28.7,80.4,7.8,alluvial,pulse,1.80
2,3,J&K,27.3,85.6,7.9,alluvial,millet,2.10
3,4,Himachal Pradesh,24.5,129.0,6.0,brown hill,rice,21.00
4,5,Himachal Pradesh,24.4,129.0,6.7,brown hill,wheat,80.00
...,...,...,...,...,...,...,...,...
66,67,Telangana,55.0,1765.0,6.7,red soil,Cotton,14.55
67,68,Telangana,45.0,1768.0,8.6,alluvial,rice,97.49
68,69,Karnataka,35.0,1786.0,7.6,red soil,rice,55.70
69,70,Karnataka,32.0,1765.0,7.5,red soil,Sugarcan,2.50
70,71,Karnataka,30.0,1876.0,7.9,red soil,pulse,15.50

In [ ]:
df.isna().sum()

S.No.          0
State          0
Temperature    0
Rainfall       0
Soil PH        0
soil type      0
Crop           0
Yeild          0
dtype: int64

In [ ]:
df.nunique()

S.No.          71
State          17
Temperature    32
Rainfall       39
Soil PH        34
soil type      13
Crop           26
Yeild          62
dtype: int64

In [ ]:
df.corr()

                S.No.  Temperature  Rainfall   Soil PH     Yeild
S.No.        1.000000     0.641262  0.870384 -0.329263 -0.206840
Temperature  0.641262     1.000000  0.552772 -0.287433 -0.034273
Rainfall     0.870384     0.552772  1.000000 -0.229192 -0.188002
Soil PH     -0.329263    -0.287433 -0.229192  1.000000  0.254150
Yeild       -0.206840    -0.034273 -0.188002  0.254150  1.000000

In [ ]:
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

sns.set_style('darkgrid')
matplotlib.rcParams['font.size']=14
matplotlib.rcParams['figure.figsize']=(10,6)
matplotlib.rcParams['figure.facecolor']='#00000000'

In [ ]:
px.histogram(df,x='Crop',title='crop type count plot')

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/btech60309-19/crop-predict

'https://jovian.ai/btech60309-19/crop-predict'

In [ ]:
px.scatter(df,x='Temperature',y='Yeild',color='Crop')

In [ ]:
input_col=list(df.columns)[1:-1]
target_col='Yeild'

In [ ]:
input_col

['State', 'Temperature', 'Rainfall', 'Soil PH', 'soil type', 'Crop']

In [ ]:
target_col

'Yeild'

In [ ]:
df_input=df[input_col]

In [ ]:
df_target=df[target_col]

In [ ]:
df_input

               State  Temperature  Rainfall  Soil PH   soil type      Crop
0                J&K         26.6      87.3      7.8    alluvial      corn
1                J&K         28.7      80.4      7.8    alluvial     pulse
2                J&K         27.3      85.6      7.9    alluvial    millet
3   Himachal Pradesh         24.5     129.0      6.0  brown hill      rice
4   Himachal Pradesh         24.4     129.0      6.7  brown hill     wheat
..               ...          ...       ...      ...         ...       ...
66         Telangana         55.0    1765.0      6.7    red soil    Cotton
67         Telangana         45.0    1768.0      8.6    alluvial      rice
68         Karnataka         35.0    1786.0      7.6    red soil      rice
69         Karnataka         32.0    1765.0      7.5    red soil  Sugarcan
70         Karnataka         30.0    1876.0      7.9    red soil     pulse

[71 rows x 6 columns]

In [ ]:
df_target

0      1.10
1      1.80
2      2.10
3     21.00
4     80.00
      ...
66    14.55
67    97.49
68    55.70
69     2.50
70    15.50
Name: Yeild, Length: 71, dtype: float64

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/btech60309-19/crop-predict

'https://jovian.ai/btech60309-19/crop-predict'

In [ ]:
import numpy as np
cat_col=df_input.select_dtypes(include=object).columns.tolist()

In [ ]:
num_col=df_input.select_dtypes(include=np.number).columns.tolist()

In [ ]:
cat_col

['State', 'soil type', 'Crop']

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/btech60309-19/crop-predict

'https://jovian.ai/btech60309-19/crop-predict'

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df_input=df_input.fillna('unknown')

In [ ]:
encoder=OneHotEncoder(sparse=False,handle_unknown="ignore")

In [ ]:
encoder.fit(df_input[cat_col])

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [ ]:
encoded_cols=list(encoder.get_feature_names(cat_col))
encoded_cols

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning:

Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.

['State_Bihar',
 'State_Chhatisgarh',
 'State_Gujarat',
 'State_Haryana',
 'State_Himachal Pradesh',
 'State_J&K',
 'State_Jharkhand',
 'State_Karnataka',
 'State_Madhya Pradesh',
 'State_Maharashtra',
 'State_Odisha',
 'State_Punjab',
 'State_Rajasthan',
 'State_Telangana',
 'State_Uttar Pradesh',
 'State_Uttrakhand',
 'State_West Bengal',
 'soil type_alkaline',
 'soil type_alluvial',
 'soil type_black soil',
 'soil type_brown hill',
 'soil type_clayey',
 'soil type_gravel',
 'soil type_mixed soil',
 'soil type_peat',
 'soil type_red soil',
 'soil type_saline',
 'soil type_sandy loam',
 'soil type_slit',
 'soil type_stiff clay',
 'Crop_Cereals',
 'Crop_Cotton',
 'Crop_Grams',
 'Crop_Maize',
 'Crop_Moong',
 'Crop_Paddy',
 'Crop_Sarson',
 'Crop_Sugarcan',
 'Crop_Sunflower',
 'Crop_bajra',
 'Crop_barley',
 'Crop_black gram',
 'Crop_coconut',
 'Crop_corn',
 'Crop_cotton',
 'Crop_jowar',
 'Crop_maize',
 'Crop_millet',
 'Crop_paddy',
 'Crop_pea',
 'Crop_pulse',
 'Crop_rice',
 'Crop_sorghum',
 'Crop_soybean',
 'Crop_vegetables',
 'Crop_wheat']

In [ ]:
len(encoded_cols)

56

In [ ]:
df_input[encoded_cols]=encoder.transform(df_input[cat_col])

In [ ]:
df_input=df_input[num_col+encoded_cols]

In [ ]:
df_input

,Temperature,Rainfall,Soil PH,State_Bihar,State_Chhatisgarh,State_Gujarat,State_Haryana,State_Himachal Pradesh,State_J&K,State_Jharkhand,...,Crop_maize,Crop_millet,Crop_paddy,Crop_pea,Crop_pulse,Crop_rice,Crop_sorghum,Crop_soybean,Crop_vegetables,Crop_wheat
0,26.6,87.3,7.8,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,28.7,80.4,7.8,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,27.3,85.6,7.9,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,24.5,129.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,24.4,129.0,6.7,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,55.0,1765.0,6.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,45.0,1768.0,8.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
68,35.0,1786.0,7.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
69,32.0,1765.0,7.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,30.0,1876.0,7.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler=MinMaxScaler()

In [ ]:
scaler.fit(df_input[num_col])

MinMaxScaler()

In [ ]:
df_input.describe().loc[['min','max']]

,Temperature,Rainfall,Soil PH,State_Bihar,State_Chhatisgarh,State_Gujarat,State_Haryana,State_Himachal Pradesh,State_J&K,State_Jharkhand,...,Crop_maize,Crop_millet,Crop_paddy,Crop_pea,Crop_pulse,Crop_rice,Crop_sorghum,Crop_soybean,Crop_vegetables,Crop_wheat
min,15.0,80.4,4.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,55.0,1876.0,8.76,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [ ]:
df_input[num_col]=scaler.transform(df_input[num_col])

In [ ]:
df_input

,Temperature,Rainfall,Soil PH,State_Bihar,State_Chhatisgarh,State_Gujarat,State_Haryana,State_Himachal Pradesh,State_J&K,State_Jharkhand,...,Crop_maize,Crop_millet,Crop_paddy,Crop_pea,Crop_pulse,Crop_rice,Crop_sorghum,Crop_soybean,Crop_vegetables,Crop_wheat
0,0.2900,0.003843,0.789474,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.3425,0.000000,0.789474,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.3075,0.002896,0.811404,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.2375,0.027066,0.394737,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.2350,0.027066,0.548246,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,1.0000,0.938182,0.548246,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,0.7500,0.939853,0.964912,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
68,0.5000,0.949877,0.745614,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
69,0.4250,0.938182,0.723684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,0.3750,1.000000,0.811404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_input.describe().loc[['min','max']]

,Temperature,Rainfall,Soil PH,State_Bihar,State_Chhatisgarh,State_Gujarat,State_Haryana,State_Himachal Pradesh,State_J&K,State_Jharkhand,...,Crop_maize,Crop_millet,Crop_paddy,Crop_pea,Crop_pulse,Crop_rice,Crop_sorghum,Crop_soybean,Crop_vegetables,Crop_wheat
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/btech60309-19/crop-predict

'https://jovian.ai/btech60309-19/crop-predict'

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_df,val_df,train_target,val_target=train_test_split(df_input,df_target,test_size=0.2,random_state=42)

In [ ]:
train_df

,Temperature,Rainfall,Soil PH,State_Bihar,State_Chhatisgarh,State_Gujarat,State_Haryana,State_Himachal Pradesh,State_J&K,State_Jharkhand,...,Crop_maize,Crop_millet,Crop_paddy,Crop_pea,Crop_pulse,Crop_rice,Crop_sorghum,Crop_soybean,Crop_vegetables,Crop_wheat
30,0.8500,0.129539,0.592105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59,0.8000,0.766652,0.328947,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
35,0.5750,0.700379,0.460526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,0.7000,0.888060,0.307018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
42,0.4000,0.707062,0.307018,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16,0.0250,0.092782,0.480263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,0.5500,0.521608,0.482456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
44,0.4750,0.704277,0.307018,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.4500,0.129539,0.328947,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.2500,0.316663,0.767544,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,0.7500,0.846291,0.548246,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
50,0.4750,0.790599,0.756579,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,0.5000,0.817331,0.285088,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,0.3250,0.567832,0.561404,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.2500,0.298842,0.921053,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57,0.7500,0.846291,0.285088,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,0.5000,0.623524,0.526316,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.3750,0.454221,0.745614,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,0.0250,0.790599,0.109649,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13,0.2750,0.316663,0.811404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,0.3750,1.000000,0.811404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.2375,0.027066,0.394737,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
17,0.2750,0.298842,0.723684,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
38,0.2750,0.512141,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8,0.2750,0.316663,0.942982,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56,0.7750,0.957674,0.438596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.2750,0.316663,0.789474,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36,0.6250,0.700379,0.482456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
65,0.7500,0.704277,0.350877,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,0.5000,0.832925,0.504386,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69,0.4250,0.938182,0.723684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0000,0.087213,0.478070,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
27,0.2750,0.129539,0.285088,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
41,0.7500,0.679216,0.307018,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.3750,0.883604,0.723684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,0.3000,0.512141,0.940789,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
24,0.3500,0.454221,0.811404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68,0.5000,0.949877,0.745614,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
64,0.5500,0.721542,0.328947,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,0.2500,0.316663,0.833333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,0.5000,0.521608,0.460526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,0.7500,0.939853,0.964912,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
62,0.6250,0.737692,0.548246,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
37,0.7000,0.700379,0.460526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.7500,0.129539,0.394737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,0.4250,0.707062,0.307018,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
66,1.0000,0.938182,0.548246,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.3425,0.000000,0.789474,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
52,0.3250,0.704277,1.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
21,0.3000,0.526064,0.789474,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.3075,0.002896,0.811404,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.2750,0.454221,0.789474,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.2750,0.298842,0.899123,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,0.6750,0.586768,0.350877,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.2750,0.316663,0.986842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,0.4250,0.789485,0.548246,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
val_df

,Temperature,Rainfall,Soil PH,State_Bihar,State_Chhatisgarh,State_Gujarat,State_Haryana,State_Himachal Pradesh,State_J&K,State_Jharkhand,...,Crop_maize,Crop_millet,Crop_paddy,Crop_pea,Crop_pulse,Crop_rice,Crop_sorghum,Crop_soybean,Crop_vegetables,Crop_wheat
22,0.3250,0.454221,0.811404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
0,0.2900,0.003843,0.789474,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,0.3000,0.456449,0.760965,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.2350,0.027066,0.548246,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
55,0.7000,0.790599,0.745614,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.3000,0.298842,0.789474,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10,0.2000,0.316663,0.745614,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0.5250,0.521608,0.482456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,0.3500,0.623524,0.445175,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,0.3250,0.316663,0.833333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,0.2750,0.521608,0.460526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.3000,0.316663,0.811404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,0.6500,0.889730,0.372807,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,0.2125,0.026509,0.438596,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,0.4750,0.901983,0.307018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components = 15)

In [ ]:
X_train = pd.DataFrame(pca.fit_transform(train_df))
X_test = pd.DataFrame(pca.transform(val_df))

In [ ]:
train_df.columns.tolist()

['Temperature',
 'Rainfall',
 'Soil PH',
 'State_Bihar',
 'State_Chhatisgarh',
 'State_Gujarat',
 'State_Haryana',
 'State_Himachal Pradesh',
 'State_J&K',
 'State_Jharkhand',
 'State_Karnataka',
 'State_Madhya Pradesh',
 'State_Maharashtra',
 'State_Odisha',
 'State_Punjab',
 'State_Rajasthan',
 'State_Telangana',
 'State_Uttar Pradesh',
 'State_Uttrakhand',
 'State_West Bengal',
 'soil type_alkaline',
 'soil type_alluvial',
 'soil type_black soil',
 'soil type_brown hill',
 'soil type_clayey',
 'soil type_gravel',
 'soil type_mixed soil',
 'soil type_peat',
 'soil type_red soil',
 'soil type_saline',
 'soil type_sandy loam',
 'soil type_slit',
 'soil type_stiff clay',
 'Crop_Cereals',
 'Crop_Cotton',
 'Crop_Grams',
 'Crop_Maize',
 'Crop_Moong',
 'Crop_Paddy',
 'Crop_Sarson',
 'Crop_Sugarcan',
 'Crop_Sunflower',
 'Crop_bajra',
 'Crop_barley',
 'Crop_black gram',
 'Crop_coconut',
 'Crop_corn',
 'Crop_cotton',
 'Crop_jowar',
 'Crop_maize',
 'Crop_millet',
 'Crop_paddy',
 'Crop_pea',
 'Crop_pulse',
 'Crop_rice',
 'Crop_sorghum',
 'Crop_soybean',
 'Crop_vegetables',
 'Crop_wheat']

In [ ]:
X_train

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,-0.122660,0.220101,0.404193,-0.248444,0.845667,0.612060,0.693927,0.180930,-0.011962,-0.383553,-0.151999,0.149716,-0.306074,-0.161547,0.146990
1,0.718062,-0.418435,0.177678,0.450717,-0.126451,-0.269327,0.464220,0.210635,0.573556,0.331120,0.224261,-0.450198,0.065364,-0.013817,0.084572
2,-0.430363,-0.180470,0.991041,-0.842697,0.079510,0.344283,-0.090305,0.231975,0.199680,0.242003,0.158052,0.148748,0.148884,-0.286052,0.105005
3,-0.535951,-0.905862,-0.419639,0.018862,-0.004559,-0.591896,0.753259,-0.061882,0.072530,-0.087453,0.218918,-0.054704,0.394290,0.065447,0.241445
4,0.902521,-0.378252,-0.115585,0.097402,0.513167,-0.071180,-0.599231,0.176364,-0.078503,0.167421,-0.301219,-0.082922,0.573253,0.187237,-0.181820
5,-0.161896,0.592771,-0.102688,0.136582,0.219857,-0.184490,0.135863,-0.309782,0.582758,0.067091,0.527722,1.055076,0.052865,0.258485,-0.511071
6,-0.511607,0.041815,0.724507,-0.727559,-0.096263,-0.003036,-0.476775,-0.086511,0.355271,0.062261,0.390417,-0.249256,0.359929,-0.233542,-0.125286
7,0.892671,-0.457619,0.386005,-0.123872,0.211669,0.465804,0.249377,0.364982,0.012462,0.194385,-0.274371,0.216283,0.369016,0.136265,0.047737
8,-0.215375,0.484788,0.081485,0.044909,0.884667,0.283887,0.395221,-0.305375,0.277670,-0.793277,-0.088081,-0.507202,-0.100203,0.190864,-0.293607
9,-0.168409,0.865725,-0.266892,-0.103722,-0.345274,-0.096568,0.110239,0.742621,-0.400527,-0.133001,0.201226,-0.027265,0.176155,0.504345,-0.260980
10,-0.476505,-0.379902,0.328842,-0.687137,-0.308572,-0.576182,0.157749,-0.226167,0.107318,-0.277784,-0.414999,-0.131608,0.267650,0.038011,0.079567
11,-0.358360,0.001478,0.415917,-0.850120,-0.292334,-0.403763,-0.299990,-0.084568,0.320796,0.059563,-0.387054,-0.152363,-0.477137,0.507142,0.067394
12,0.777150,-0.474495,-0.253946,0.029601,-0.307984,0.675857,-0.187393,-0.001039,0.251460,-0.077898,-0.375768,-0.147459,0.594359,0.180509,-0.146150
13,-0.212594,-0.021023,0.675363,-0.790084,0.187462,0.195059,0.021674,0.335636,0.196495,0.207080,-0.295894,0.579067,-0.302368,-0.070119,0.305965
14,0.822896,0.074853,-0.425713,-0.076817,-0.526278,0.511890,-0.271319,-0.199021,0.196280,-0.504824,0.117300,0.097144,-0.285909,-0.357088,0.224313
15,0.675584,-0.658733,0.375734,-0.151357,0.214385,0.264890,0.726931,0.331350,0.004867,0.289537,0.226411,0.162289,0.114537,0.096868,0.362824
16,-0.617263,-0.516135,-0.800063,0.248108,-0.190701,0.579458,-0.243131,-0.036453,0.322053,-0.160155,0.000230,0.083214,-0.121457,0.331711,0.390736
17,-0.117068,0.340341,-0.557803,-0.162520,-0.530683,0.857993,-0.059599,-0.634570,-0.028420,0.146733,-0.316109,0.183598,0.046288,0.053473,-0.254161
18,-0.378422,-0.050648,0.501946,1.259916,-0.210545,-0.071237,-0.309494,0.045247,0.357416,0.193387,-0.238231,-0.033470,-0.188358,0.391776,0.227840
19,-0.232365,0.669314,-0.621243,-0.115880,-0.643747,0.690969,-0.087626,0.351476,0.006987,-0.347771,-0.267219,0.154467,0.278820,-0.005181,-0.002676
20,-0.615852,-0.738514,-0.684588,-0.131792,-0.216146,-0.658872,0.271160,-0.109649,-0.205648,-0.211147,-0.144773,0.100673,-0.021022,-0.462735,-0.048551
21,-0.038101,0.347308,-0.210280,0.106215,0.852615,-0.257401,-0.716171,0.064595,-0.054677,-0.134936,-0.095461,0.433699,0.222907,0.000149,-0.138682
22,0.948369,0.196253,0.059754,0.420942,-0.323043,-0.211193,-0.086177,0.055394,0.554477,-0.123811,0.176545,-0.195752,-0.486449,-0.445454,0.135288
23,-0.518779,-0.497471,-0.593625,0.442005,0.752147,-0.129717,-0.648706,0.131281,0.119287,0.101068,0.046544,0.172311,0.027933,0.459419,0.373577
24,-0.191290,0.829530,-0.251619,-0.115890,-0.302634,-0.104532,0.064851,0.661804,-0.269561,-0.210949,0.099273,0.053829,0.130025,0.085026,0.077479
25,-0.611386,-0.733993,-0.757400,-0.097062,-0.312125,0.521627,0.050654,-0.035355,0.257696,-0.111286,-0.163000,-0.156093,0.075839,-0.089979,-0.017833
26,-0.118388,1.058934,-0.172410,0.398645,-0.247048,-0.329055,0.203440,0.513769,0.237441,0.445369,-0.234777,-0.374954,0.070737,-0.388343,0.373375
27,-0.532194,-0.061417,0.737378,-0.740618,-0.129984,0.002652,-0.463915,-0.070874,0.317261,0.127080,0.362449,-0.321670,0.350204,-0.223748,-0.143069
28,0.728773,-0.526765,0.365516,-0.246731,0.276986,0.384927,0.401502,0.423064,-0.325452,0.206057,0.099823,0.081224,-0.354153,-0.029293,-0.068083
29,-0.373397,-0.274180,0.875120,0.469493,-0.034203,0.369738,0.345434,0.188568,-0.613288,0.104198,-0.458929,0.568268,-0.242329,-0.188301,-0.085894
30,-0.607749,-0.643504,-0.990936,-0.083973,-0.344001,0.381605,-0.100289,0.004474,0.144493,-0.070313,-0.140796,0.061629,-0.174352,-0.475564,-0.107902
31,0.003197,0.625661,0.096956,0.602287,-0.019059,-0.349386,0.014267,0.092575,1.030818,0.050445,0.014934,0.406850,-0.241226,-0.178125,-0.501298
32,-0.138513,0.646962,-0.229127,0.122859,1.202209,-0.106133,-0.225622,-0.187547,-0.078460,0.048785,-0.344295,-0.216229,0.188218,-0.238941,0.308151
33,-0.519582,-0.241184,0.526159,0.866338,-0.090687,0.255777,-0.380952,-0.207797,-0.389077,-0.176446,0.306051,-0.073961,-0.197274,0.606877,0.555583
34,0.735363,0.012170,-0.146810,-0.166284,-0.327069,0.067623,0.077674,-0.479924,-0.441035,0.508495,0.085248,-0.133251,-0.079290,0.376453,-0.325131
35,0.791720,-0.039225,-0.201738,-0.157446,0.431251,-0.279548,-0.658264,0.119927,-0.303716,0.045488,-0.096750,0.251975,-0.135045,-0.142700,0.035864
36,-0.149411,0.731461,-0.310571,-0.085379,0.056116,-0.032223,0.322683,-0.818233,-0.190209,0.950698,0.131770,0.187797,0.040281,-0.017564,0.114530
37,-0.503305,-0.644046,-0.832976,-0.032740,0.465532,-0.348365,-0.481398,0.195303,-0.221588,0.210524,-0.070547,0.049809,-0.202193,-0.466726,-0.156960
38,-0.493461,-0.329647,0.575653,0.632460,-0.306480,-0.424293,0.311811,-0.308593,-0.645169,-0.393194,-0.517840,0.271633,0.220162,-0.095741,-0.199969
39,-0.232683,1.069895,-0.323214,-0.046643,-0.115828,-0.166042,0.171919,0.393060,-0.307134,0.287485,-0.102777,-0.178963,0.290769,-0.236025,0.597514
40,-0.530028,0.005157,0.767229,0.362705,-0.151714,0.190248,-0.366485,-0.200933,-0.322434,-0.080969,0.459661,-0.097483,0.403817,-0.290069,-0.278862
41,0.753753,-0.444056,-0.211967,-0.170931,0.391622,-0.205991,-0.470033,0.257012,-0.582335,0.234634,0.060530,-0.271543,-0.348523,-0.100397,-0.329774
42,-0.334309,-0.046069,0.683593,1.067015,-0.366566,-0.155892,0.096995,0.069507,-0.051040,0.139789,-0.451727,-0.063604,-0.291900,-0.301563,-0.365869
43,-0.538604,-0.139771,0.838134,0.436271,-0.219631,0.255775,-0.432564,-0.251155,-0.466647,-0.132848,0.663820,-0.246704,0.193041,-0.153060,0.055816
44,-0.238278,0.475439,0.079827,-0.003224,0.904622,0.324452,0.497601,-0.431795,0.166332,-0.662652,-0.096831,-0.693293,-0.149179,0.122983,-0.249378
45,0.931823,-0.236441,0.187321,0.491354,-0.142246,-0.076883,-0.030996,0.245362,0.590559,0.264378,-0.300524,-0.383517,0.331620,0.041626,-0.230738
46,-0.503354,-0.699381,-0.467881,-0.112272,0.121125,-0.003255,0.259742,0.441591,-0.306751,0.216738,0.438341,-0.470029,-0.550574,0.064715,-0.522248
47,0.763280,0.049472,-0.068102,-0.133456,-0.163520,-0.639204,0.268815,-0.359593,-0.212950,-0.796206,0.088379,0.310923,0.307335,-0.125290,0.150856
48,-0.324477,0.134441,0.359951,-0.892704,-0.350199,-0.447387,-0.346021,-0.093983,0.295427,0.022711,-0.376854,-0.067269,-0.567420,0.436550,0.072999
49,0.786606,0.147998,-0.153271,-0.150804,-0.229025,0.073216,0.046748,-0.631617,-0.320527,0.399897,0.105463,-0.007662,-0.138774,0.172092,-0.205294
50,0.864190,0.267355,-0.064349,-0.090195,-0.029021,-0.198456,-0.004053,-0.192103,-0.066310,-0.547056,0.360590,0.289977,0.032832,-0.089645,0.088401
51,-0.118684,0.776860,-0.258896,-0.097877,0.109515,0.063155,0.264912,-0.832876,-0.314812,0.751774,-0.192918,-0.291916,-0.060827,-0.122334,0.175926
52,0.841828,0.136129,0.022961,0.077535,-0.272072,0.035624,-0.293776,-0.216232,-0.120001,-0.447437,0.636241,-0.041641,-0.483325,-0.202729,0.482583
53,-0.509040,-0.517452,-0.490752,0.089493,0.245612,-0.171231,0.635010,-0.054043,0.379380,0.365142,0.737833,0.222250,0.177958,0.213916,0.096343
54,-0.233268,0.853085,-0.325493,-0.151892,-0.347120,-0.127853,0.130538,0.900199,-0.433333,-0.193796,0.294211,-0.116793,-0.049316,0.339852,-0.337767
55,0.575181,-0.400608,0.071312,-0.283589,-0.342919,-0.717978,0.186065,-0.301030,-0.169205,-0.382576,-0.332502,-0.053674,0.049590,0.329882,0.110379

In [ ]:
X_test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.850608,0.245064,-0.027010,0.292705,-0.349349,-0.125995,0.092874,-0.367809,0.222076,0.516165,-0.051789,-0.223033,-0.279266,-0.098065,-0.220846
1,0.812628,0.248455,-0.057836,-0.076001,-0.022091,-0.172343,-0.005605,-0.165340,-0.050019,-0.461097,0.290365,0.235141,0.032350,-0.062496,0.066838
2,-0.152960,0.283018,0.446838,-0.215049,-0.189511,-0.361529,-0.262950,0.211903,0.745879,0.235771,-0.294724,-0.001017,-0.397359,-0.214187,0.028251
3,0.002649,0.526741,0.067757,0.469152,0.158704,-0.280612,-0.161367,0.134118,0.585909,-0.041597,-0.092458,0.144996,-0.065646,-0.177871,-0.190560
4,-0.538817,-0.492666,-0.476534,-0.127563,-0.046914,-0.065250,0.144760,0.033777,0.053218,0.004066,0.082732,-0.150087,-0.105172,-0.074180,-0.035318
5,0.920124,0.054980,-0.248077,0.009466,0.320305,-0.206160,-0.648619,-0.011240,-0.133806,-0.223241,0.182424,0.091446,-0.265722,-0.315197,0.180759
6,-0.187804,0.751528,-0.210639,-0.057751,-0.228145,-0.080532,0.052689,0.562492,-0.180107,-0.171941,0.067664,0.060552,0.162364,0.108480,0.065295
7,-0.452214,0.013130,0.695958,0.308861,-0.163545,0.175614,-0.306902,-0.261561,-0.329502,-0.007354,0.396005,-0.086055,0.274002,-0.182160,-0.261426
8,-0.332957,0.023903,0.453040,0.308609,-0.076990,-0.024897,-0.230568,-0.065441,-0.251884,-0.024959,-0.184841,0.260232,-0.241232,0.138569,-0.002026
9,-0.223574,0.976858,-0.291535,-0.047472,-0.097850,-0.135995,0.162601,0.339342,-0.269723,0.241789,-0.076673,-0.164775,0.224026,-0.179980,0.441530
10,-0.484619,0.061553,0.687674,0.344613,-0.151362,0.140442,-0.358793,-0.179935,-0.248666,-0.065059,0.352893,-0.010175,0.315378,-0.213671,-0.199360
11,-0.199228,0.751934,-0.281858,-0.093710,-0.331427,0.140951,0.039040,0.431210,-0.167902,-0.173622,-0.049594,0.090378,0.184940,0.082941,-0.025712
12,-0.231015,-0.209101,0.082890,-0.047943,0.222113,-0.054722,0.482643,-0.054213,0.248538,-0.016270,0.144406,-0.390634,0.003355,0.385885,-0.028627
13,-0.039123,0.300971,0.275717,-0.117693,0.533063,0.264349,0.111341,0.250308,0.038321,-0.106935,-0.076649,0.763445,0.006373,-0.057785,0.093149
14,-0.358863,-0.265280,0.171766,-0.527066,0.365171,-0.295361,-0.661819,0.069641,0.158826,0.187536,-0.399860,-0.087720,0.141798,0.086715,-0.016498

In [ ]:
train_target

30    172.00
59     32.80
35      7.07
58      9.80
42     37.40
16     14.78
34      4.74
44     18.40
28     77.50
7      40.00
54     20.00
50     44.00
45      1.10
47     11.00
19     87.00
57     11.20
40      2.20
25     76.80
39      5.70
13    340.00
70     15.50
3      21.00
17     80.00
38     22.30
8       3.80
56      2.10
6     100.00
36     20.04
65     36.38
63     18.24
69      2.50
15     11.28
27      1.10
41     32.00
26     76.00
48     12.00
24     54.91
68     55.70
64     23.06
11     20.00
32      3.14
67     97.49
62     11.81
37     13.99
29     47.80
43     22.70
66     14.55
1       1.80
52      1.42
21      9.80
2       2.10
23     55.80
20     35.00
60      2.40
14      1.50
51      7.38
Name: Yeild, dtype: float64

In [ ]:
val_target

22    160.00
0       1.10
49     20.00
4      80.00
55      7.70
18     90.00
10      5.00
33      2.03
46     17.00
12     20.00
31      5.25
9      20.00
61      3.20
5       4.00
53     16.00
Name: Yeild, dtype: float64

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/btech60309-19/crop-predict

'https://jovian.ai/btech60309-19/crop-predict'

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/btech60309-19/crop-predict

'https://jovian.ai/btech60309-19/crop-predict'

In [ ]:
from sklearn.svm import SVR

In [ ]:
classifier=SVR(kernel='rbf',shrinking=True)

In [ ]:
classifier.fit(X_train,train_target)

SVR()

In [ ]:
predict_train=classifier.predict(X_train)
predict_train

array([19.42436566, 19.29004246, 16.89842854, 16.06962561, 19.48589291,
       17.11529699, 17.33316804, 18.49973016, 20.25977531, 18.48753261,
       17.75057671, 18.1136514 , 18.41103981, 17.2662333 , 19.38394117,
       17.94498855, 16.77442857, 19.3823213 , 17.58626391, 19.15184687,
       16.34533886, 19.01063049, 19.83785976, 18.73907549, 18.63488013,
       16.05787712, 19.89064479, 17.33912133, 18.81813342, 18.13973011,
       16.3038691 , 17.53539975, 19.32532169, 18.30505732, 19.27798252,
       19.04762813, 20.03328589, 18.10937392, 18.21230761, 19.90053976,
       16.86821457, 19.51968128, 17.50476612, 17.01761455, 20.37884488,
       19.68880999, 16.99263104, 17.13992161, 18.09892392, 19.32923073,
       18.0791143 , 20.51147478, 19.33348271, 16.28733063, 18.26823713,
       17.51682934])

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(train_target, predict_train)

2991.1676467342477

In [ ]:
predict_test=classifier.predict(X_test)
predict_test

array([19.75926221, 18.21832753, 18.03107225, 18.27167159, 16.30203993,
       19.1862623 , 18.66181134, 17.03056586, 17.86454785, 19.84943528,
       16.97078035, 18.8980403 , 17.98174408, 18.10321222, 18.32904864])

In [ ]:
mean_squared_error(val_target, predict_test)

1989.146241520704

In [ ]:
val_target

22    160.00
0       1.10
49     20.00
4      80.00
55      7.70
18     90.00
10      5.00
33      2.03
46     17.00
12     20.00
31      5.25
9      20.00
61      3.20
5       4.00
53     16.00
Name: Yeild, dtype: float64

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/btech60309-19/crop-predict

'https://jovian.ai/btech60309-19/crop-predict'

In [ ]:
jovian.commit